import { createTamagui, createTokens, createFont } from '@tamagui/core';
import { createAnimations } from '@tamagui/animations-react-native';
import { Easing } from 'react-native-reanimated';

export const animations = createAnimations({
  fast: {
    type: 'spring',
    damping: 20,
    mass: 1.2,
    stiffness: 250,
  },
  medium: {
    type: 'spring',
    damping: 10,
    mass: 0.9,
    stiffness: 100,
  },
  slow: {
    type: 'spring',
    damping: 20,
    mass: 1,
    stiffness: 60,
  },
  fastScale: {
    type: 'timing',
    duration: 50, 
    easing: Easing.linear, 
  },
});

export const tokens = createTokens({
  size: {
    $0: 0,
    '$0.25': 2,
    '$0.5': 4,
    '$0.75': 8,
    $1: 12,
    '$1.5': 16,
    $2: 20,
    '$2.5': 24,
    $3: 28,
    '$3.5': 32,
    $4: 36,
    '$4.5': 40,
    $5: 44,
    '$5.5': 48,
    $6: 52,
    '$6.5': 56,
    $7: 60,
    '$7.5': 64,
    $8: 68,
    '$8.5': 72,
    $9: 76,
    '$9.5': 80,
    $10: 84,
    true: 84,
  },
  space: {
    $0: 0,
    '$0.25': 2,
    '$0.5': 4,
    '$0.75': 8,
    $1: 12,
    '$1.5': 16,
    $2: 20,
    '$2.5': 24,
    $3: 28,
    '$3.5': 32,
    $4: 36,
    '$4.5': 40,
    $5: 44,
    '$5.5': 48,
    $6: 52,
    '$6.5': 56,
    $7: 60,
    '$7.5': 64,
    $8: 68,
    '$8.5': 72,
    $9: 76,
    '$9.5': 80,
    $10: 84,
    true: 84,
  },
  radius: {
    $0: 0,
    '$0.25': 2,
    '$0.5': 4,
    '$0.75': 8,
    $1: 12,
    '$1.5': 16,
    $2: 20,
    '$2.5': 24,
    $3: 28,
    '$3.5': 32,
    $4: 36,
    '$4.5': 40,
    $5: 44,
    '$5.5': 48,
    $6: 52,
    '$6.5': 56,
    $7: 60,
    '$7.5': 64,
    $8: 68,
    '$8.5': 72,
    $9: 76,
    '$9.5': 80,
    $10: 84,
    true: 84,
  },
  zIndex: {
    $0: 0,
    $1: 100,
    $2: 200,
    $3: 300,
    $4: 400,
    $5: 500,
    true: 500,
  },
  color: {
    white: '#FFFFFF',
    black: '#000000',
    blue: '#0000FF',
    yellow: '#FFFF00',
    gray: '#808080',
    grayLight: '#D3D3D3',
    grayDark: '#A9A9A9',
  },
});

const font = createFont({
  family: 'System',
  size: {
    $1: 12,
    $2: 14,
    $3: 16,
    $4: 18,
    $5: 20,
    $6: 24,
    $7: 28,
    $8: 32,
    $9: 36,
    $10: 40,
    true: 16,
  },
  lineHeight: {
    $1: 16,
    $2: 20,
    $3: 24,
    $4: 28,
    $5: 32,
    $6: 36,
    $7: 40,
    $8: 44,
    $9: 48,
    $10: 52,
    true: 24,
  },
  weight: {
    $1: '300',
    $2: '400',
    $3: '500',
    $4: '600',
    $5: '700',
    $6: '800',
    $7: '900',
    true: '400',
  },
});

export const defaultTheme = {
  bg: tokens.color.white,
  bg2: tokens.color.grayLight,
  bg3: tokens.color.gray,
  color: tokens.color.black,
  color2: tokens.color.grayDark,
  color3: tokens.color.gray,
  borderColor: tokens.color.grayLight,
  borderColor2: tokens.color.gray,
  shadowColor: tokens.color.gray,
  primary: tokens.color.blue,
  secondary: tokens.color.yellow,
};

export const darkTheme = {
  bg: tokens.color.black,
  bg2: tokens.color.grayDark,
  bg3: tokens.color.gray,
  color: tokens.color.white,
  color2: tokens.color.grayLight,
  color3: tokens.color.grayLight,
  borderColor: tokens.color.grayDark,
  borderColor2: tokens.color.gray,
  shadowColor: tokens.color.black,
  primary: tokens.color.yellow,
  secondary: tokens.color.blue,
};

const config = createTamagui({
  animations,
  tokens,
  fonts: {
    heading: font,
    body: font,
  },
  themes: {
    light: defaultTheme,
    dark: darkTheme,
  },
  settings: {
    allowedStyleValues: 'somewhat-strict',
  },
  shorthands: {
    ac: 'alignContent',
    ai: 'alignItems',
    als: 'alignSelf',
    b: 'bottom',
    bc: 'backgroundColor',
    br: 'borderRadius',
    f: 'flex',
    fd: 'flexDirection',
    fs: 'flexShrink',
    fw: 'flexWrap',
    h: 'height',
    jc: 'justifyContent',
    l: 'left',
    m: 'margin',
    mb: 'marginBottom',
    ml: 'marginLeft',
    mr: 'marginRight',
    mt: 'marginTop',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    p: 'padding',
    pb: 'paddingBottom',
    pl: 'paddingLeft',
    pr: 'paddingRight',
    pt: 'paddingTop',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    r: 'right',
    t: 'top',
    ta: 'textAlign',
    w: 'width',
    zi: 'zIndex',
  },
});

export type AppConfig = typeof config;

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config